# Generated by Django 3.1 on 2020-08-09 04:28

from django.db import migrations, models
import django.db.models.deletion
import document.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='document_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='parent_document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('event_date', models.DateField()),
                ('published', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Correspondence_document',
            fields=[
                ('parent_document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='document.parent_document')),
                ('Issuer', models.CharField(max_length=150)),
                ('Destination', models.CharField(max_length=150)),
            ],
            bases=('document.parent_document',),
        ),
        migrations.CreateModel(
            name='decision_document',
            fields=[
                ('parent_document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='document.parent_document')),
                ('boss_name', models.CharField(max_length=150)),
                ('decision_type', models.CharField(max_length=150)),
            ],
            bases=('document.parent_document',),
        ),
        migrations.CreateModel(
            name='preparator_document',
            fields=[
                ('parent_document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='document.parent_document')),
                ('boss_name', models.CharField(max_length=150)),
                ('meeting_type', models.CharField(max_length=150)),
            ],
            bases=('document.parent_document',),
        ),
        migrations.CreateModel(
            name='report_document',
            fields=[
                ('parent_document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='document.parent_document')),
                ('Issuer', models.CharField(max_length=150)),
                ('Destination', models.CharField(max_length=150)),
            ],
            bases=('document.parent_document',),
        ),
        migrations.CreateModel(
            name='warrant_document',
            fields=[
                ('parent_document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='document.parent_document')),
                ('Issuer', models.CharField(max_length=150)),
                ('Destination', models.CharField(max_length=150)),
            ],
            bases=('document.parent_document',),
        ),
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file_uploded', models.FileField(upload_to=document.models.Management_path)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.employee')),
                ('select_cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.cabinet')),
            ],
        ),
    ]
