# Generated by Django 3.1 on 2020-08-09 04:37

from django.db import migrations, models
import django.db.models.deletion
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent_document',
            name='file_uploded',
            field=models.FileField(default=1, upload_to=document.models.Management_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent_document',
            name='select_cabinet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cabinet.cabinet'),
            preserve_default=False,
        ),
    ]
