# Generated by Django 3.1 on 2020-08-08 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
        ('tags', '0001_initial'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='warrant_document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('event_date', models.DateField()),
                ('published', models.DateField(auto_now_add=True)),
                ('warrant_creator', models.CharField(max_length=150)),
                ('Destination', models.CharField(max_length=150)),
                ('management_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.cabinet')),
                ('tags', models.ManyToManyField(to='tags.Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='report_document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('event_date', models.DateField()),
                ('published', models.DateField(auto_now_add=True)),
                ('Issuer', models.CharField(max_length=150)),
                ('Destination', models.CharField(max_length=150)),
                ('management_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.cabinet')),
                ('tags', models.ManyToManyField(to='tags.Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='decision_document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('event_date', models.DateField()),
                ('published', models.DateField(auto_now_add=True)),
                ('boss_name', models.CharField(max_length=150)),
                ('decision_type', models.CharField(max_length=150)),
                ('management_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.cabinet')),
                ('tags', models.ManyToManyField(to='tags.Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Correspondence_document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('event_date', models.DateField()),
                ('published', models.DateField(auto_now_add=True)),
                ('Issuer', models.CharField(max_length=150)),
                ('Destination', models.CharField(max_length=150)),
                ('management_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.cabinet')),
                ('tags', models.ManyToManyField(to='tags.Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
