# Generated by Django 3.1 on 2020-08-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20200809_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='select_cabinet',
        ),
        migrations.DeleteModel(
            name='document_type',
        ),
        migrations.RenameField(
            model_name='decision_document',
            old_name='boss_name',
            new_name='Issuer',
        ),
        migrations.RenameField(
            model_name='parent_document',
            old_name='published',
            new_name='published_at',
        ),
        migrations.RenameField(
            model_name='warrant_document',
            old_name='Issuer',
            new_name='Issuer_creator',
        ),
        migrations.AddField(
            model_name='parent_document',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='parent_document',
            name='select_cabinet',
        ),
        migrations.DeleteModel(
            name='document',
        ),
        migrations.AddField(
            model_name='parent_document',
            name='select_cabinet',
            field=models.ManyToManyField(to='document.Tags'),
        ),
    ]
