# Generated by Django 3.0.7 on 2020-08-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_preparator_dcument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparator_dcument',
            name='create_date',
            field=models.DateField(),
        ),
    ]
