# Generated by Django 3.1 on 2020-08-13 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
        ('document', '0003_auto_20200813_0429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent_document',
            old_name='select_cabinet',
            new_name='select_tag',
        ),
        migrations.AddField(
            model_name='parent_document',
            name='select_managment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cabinet.cabinet'),
            preserve_default=False,
        ),
    ]
