# Generated by Django 3.0.7 on 2020-08-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20200808_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparator_dcument',
            name='Event_date',
            field=models.DateField(auto_now=True),
        ),
    ]
