# Generated by Django 3.1 on 2020-08-13 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet',
            name='employee',
        ),
        migrations.DeleteModel(
            name='employee',
        ),
    ]
